server:
  port: ${random.int(40001,49999)}

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址

  # 邮箱相关
  mail:
    host: xxx
    username: xxx
    password: xxx
    port: 000
    default-encoding: UTF-8
    properties:
      mail:
        #        debug: true # 开启发送邮件debug模式
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
