server:
  port: ${random.int(40001,49999)}

mybatis-plus:
  type-aliases-package: cn.sticki.resource.pojo  # 实体对象的扫描包

spring:
  # servlet文件传输限制
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
