spring:
  rabbitmq:
    host: xxxx # 主机名
    port: xxxx # 端口
    virtual-host: xxxx # 虚拟主机
    username: xxxx # 用户名
    password: xxxx # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息